### PR TITLE
Bad file path

### PR DESCRIPTION
**Pull request by davidrenne**

### CODE REVIEW

**Comment by davidrenne** [comment]
@Red5d 

Most likely this Dockerfile needs this

```
FROM alpine:latest

WORKDIR /usr/src/app

# Copy the files into the container
COPY . .
COPY requirements.txt .

# Install dependencies using separate RUN commands for better debugging
RUN apk update && apk add --no-cache py3-numpy py3-pillow py3-requests mediainfo python3 ffmpeg && python3 -m venv /usr/src/venv && source /usr/src/venv/bin/activate && pip install --upgrade pip setuptools && pip install -r requirements.txt

# Change the working directory
WORKDIR /edit

# Define the entry point
CMD ["/bin/sh"]

```

I changed the ENTRYPOINT to CMD, as I wasnt sure how you use it and when I had your entry point it errored in my image.  Play around with this in your localhost on the latest docker and maybe make some updates to anyone coming across this project.

Many things are deprecated I found.  I didnt end up using this container much, I was using stuff on OSX copying libmediainfo.dylib and getting many errors on my EDL file for the MP4 processing.  But all I needed for my use case was the initial MP3 of the cuts I needed off an MP4 and I was going to regenerate the MP4 my own way rather than relying on unstable python stuff that errored quite a bit for my files.

Still a very useful project for processing EDL files!  I know you guys dont maintain it much, but the requirements.txt needs this too:

```
moviepy
pymediainfo
imageio-ffmpeg
```

I did a ton of youtube API automations and subsequently my project involves cropping lots of youtube copyright segments, so I convert their data into an EDL file format and autocrop and re-upload.

Kind of a fun project in golang and a bit of python with this project.

**Comment by davidrenne** [comment]
@Red5d 

Two things I kinda need help with.  I am finding if I set a zero value in my edl like this:

```
0 230 0
1344 1449 0
```

I get an index out of range.  

I can adjust my go script and shell scripts to set this to a value of 1 no problem, but thought it might be a sane default when parsing or passing an EDL file to moviepy.

I also am not getting good results overall in producing the video, my audio is muted on all my tests (hundreds), so I CTRL+C and just get the audio and I regenerate the video from the audio.  Since I am working with just an image background this is fine.

But I was wondering if you had any insight as to how to configure the python calls to just have moviepy generate audioonly.  

I want to automate this portion because I have 30000 videos to run through your python code.  LOL  I dont want to have to CTRL+C the audio if I can just have this clip tool generate an audio only.

Thank you for your advice on setting sane defaults when parsing an EDL within your python package to prevent the zero from index failing.

**Comment by Red5d** [comment]
Ok, sure. The zero issue should be fixable. 

And for clarification, you're getting muted/no audio in the resulting file after running it through edledit to cut out the sections listed in your EDL?

For the part about having moviepy generate only audio, that should be doable, though I don't think I have a method for doing that currently implemented in this tool. I remember seeing moviepy documentation about it I think.

**Comment by davidrenne** [comment]
Chat gpt kinda wrote this and its working fine if you ever wanna just add an edlAudioOnly.py

```
from moviepy.editor import *
import sys, os, re, edl, tempfile, argparse
from pymediainfo import MediaInfo

def render(videofile, estruct, outfile, videoBitrate="2000k", audioBitrate="400k", ffmpegPreset="medium", vcodec=None, acodec=None, ffmpeg_params=None, writeLogfile=False):
    global prevTime
    prevTime = 0
    audio_clips = []

    v = VideoFileClip(videofile)
    duration = v.duration

    for edit in estruct.edits:
        nextTime = float(edit.time1)
        time2 = float(edit.time2)
        action = edit.action

        if nextTime > duration:
            nextTime = duration

        if prevTime > duration:
            prevTime = duration

        clip = v.subclip(prevTime, nextTime)
        audio_clips.append(clip.audio)
        print("created subclip from " + str(prevTime) + " to " + str(nextTime))

        prevTime = nextTime
        nextTime = time2

        if action == "1":
            # Muting audio only. Add a silent audio clip.
            audio_clips.append(AudioClip.make_silence(duration=(nextTime - prevTime)))
            print("created muted subclip from " + str(prevTime) + " to " + str(nextTime))

            # Advance to next segment time.
            prevTime = nextTime

        elif action == "0":
            print("Cut video from " + str(prevTime) + " to " + str(nextTime) + ".")
            prevTime = nextTime

        elif action == "2":
            # Cut audio and speed up video to cover it.
            s1 = v.subclip(prevTime, nextTime).without_audio()
            s2 = v.subclip(nextTime, (nextTime + s1.duration))

            # Put the clips together, speed them up, and use the audio from the second segment.
            audio_clips.append(s1.audio)
            audio_clips.append(s2.audio)
            print("Cutting audio from " + str(prevTime) + " to " + str(nextTime) + " and squeezing video from " + str(prevTime) + " to " + str(nextTime + s1.duration) + " into that slot.")
            # Advance to next segment time (+time from speedup)
            prevTime = nextTime + s1.duration

        else:
            clip = v.subclip(prevTime, nextTime)
            audio_clips.append(clip.audio)
            prevTime = nextTime

    audio = concatenate_audioclips(audio_clips)

    if ffmpeg_params is not None:
        fparams = []
        for x in ffmpeg_params.split(' '):
            fparams.extend(x.split('='))
    else:
        fparams = None

    audio.write_audiofile(outfile, codec=acodec, bitrate=audioBitrate, ffmpeg_params=fparams)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("infile", help="Original input video file.")
    parser.add_argument("edlfile", help="EDL file with edit definitions.")
    parser.add_argument("outfile", help="Edited video file path/name.")
    parser.add_argument("-p", "--preset", choices=["ultrafast", "superfast", "fast", "medium", "slow", "superslow"], help="FFMPEG preset to use for optimizing the compression. Defaults to 'medium'.")
    parser.add_argument("-vb", "--videobitrate", help="Video bitrate setting. Auto-detected from original video unless specified.")
    parser.add_argument("-ab", "--audiobitrate", help="Audio bitrate setting. Auto-detected from original video unless specified.")
    parser.add_argument("-vc", "--vcodec", help="Video codec to use.")
    parser.add_argument("-ac", "--acodec", help="Audio codec to use.")
    parser.add_argument("-fp", "--ffmpegparams", help="Additional FFMpeg parameters to use. Example: '-crf=24 -s=640x480'.")
    args = parser.parse_args()

    estruct = edl.EDL(args.edlfile)

    videoBitrate = ""
    audioBitrate = ""
    
    if args.preset == None:
        ffmpegPreset = "medium"
    else:
        ffmpegPreset = args.preset

    mi = MediaInfo.parse(args.infile)
    if args.videobitrate == None:
        videoBitrate = str(int(mi.tracks[1].bit_rate / 1000)) + "k"
        print("Using original video bitrate: "+videoBitrate)
    else:
        videoBitrate = args.videobitrate
        if videoBitrate[-1] != 'k':
            videoBitrate = videoBitrate+'k'

    if args.audiobitrate == None:
        try:
            audioBitrate = str(int(mi.tracks[2].bit_rate / 1000)) + "k"
        except TypeError:
            audioBitrate = str(int(int(mi.tracks[2].bit_rate.split(' / ')[1]) / 1000)) + "k"

        print("Using original audio bitrate: "+audioBitrate)
    else:
        audioBitrate = args.audiobitrate
        if audioBitrate[-1] != 'k':
            audioBitrate = audioBitrate+'k'

    render(args.infile, estruct, args.outfile, videoBitrate, audioBitrate, vcodec=args.vcodec, acodec=args.acodec, ffmpeg_params=args.ffmpegparams, ffmpegPreset=ffmpegPreset)



if __name__ == "__main__":
    main()
    

```

The AI took out the threads, but thats fine for my purposes, I will use go to exec maybe 10-15 mp4 slicing and dicing at a time until all my execs are done.

Now I dont have to CTRL+C to get my audio cut!

This project is really cool.  Thank you for all the automations!

Also one other thing to note.  Sometimes in my calculation a movie file for the EDL is slightly higher in seconds to the MP4 and that panics a bit in the python side.  So I manually adjust the backside of the EDL to crop out less seconds.  Not sure if you can do anything about that.

**Comment by davidrenne** [comment]
I did finally get my go code to call the python shell stuff and it processed a few hundred mp4's of removing copyright for youtube stuff that they identified.  If you think it would be useful to port such a utility to kind of "copy/paste" the start/end of copyright clips on youtube to an EDL file in python, its very basic.  But nice utility.  I know this is more of a command line facility, but perhaps you could read the clipboard of a raw copy of copyright of youtube and output an EDL file like I am doing.

I wrote mine in go if you want the source and I daisy chained it all together within your python stuff to convert to MP3 a clean no copyright mix and then I just recreate the MP4 off that since I was having problems a bit on the audio reembedding back in with ffmpeg with this tool

**Comment by davidrenne** [comment]
Obviously some hard coded paths and its not generic.  It was just duct tape coding a solution for now.  I dont use this main anymore now that this thing is fully automated, I dump the copyright info from youtube into the description and use APIs to upload stuff and process and transfer data using your tool in the middle to crop sections of the originl.

You'll get the gist with the parsing and conversion of youtube copyright clips into edl files.  It definitely could have its place in this repo to just read whats in the clipboard and output a file to help someone:

Mine was just a bit hack n' slash that I would copy my mp4 path that I knew correlated with the youtube file to string together a command

```
package main

import (
	"fmt"
	"log"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/atotto/clipboard"
)

var prevClipboardData string // To store previous clipboard data
var syncClip sync.RWMutex

func main() {
	go massageClipboard()
	select {}
}

func massageClipboard() {
	// Run indefinitely
	lastKnownPath := ""
	for {
		syncClip.RLock()
		clipboardData, err := clipboard.ReadAll()
		syncClip.RUnlock()
		if err != nil {
			fmt.Println("Error:", err)
			continue
		}

		// Split clipboard data by lines
		lines := strings.Split(clipboardData, "\n")

		// Flag to track if any changes were made
		updated := false

		// Iterate over each line
		var out string
		typeContent := ""

		if strings.Contains(clipboardData, "/Volumes/") {
			lastKnownPath = clipboardData
		}
		if strings.Contains(clipboardData, "Content found") {
			updated = true
			typeContent = "content"
			out = genEDLFromYoutubeMetaData(lines)
		} else {
			continue
		}

		// If any changes were made, update the clipboard
		if updated {

			if typeContent == "content" {
				//if output.edl exists, delete it
				_, err := os.Stat("output.edl")
				if err == nil {
					err = os.Remove("output.edl")
					if err != nil {
						log.Fatal("Cannot delete file", err)
					}
				}

				file, err := os.Create("output.edl")
				if err != nil {
					log.Fatal("Cannot create file", err)
				}
				fmt.Fprint(file, out)
				file.Close()
				clipboard.WriteAll("cd /Users/davidrenne/Atlona/ahYoutube/edlkit && python3 edledit.py " + lastKnownPath + " /Users/davidrenne/Atlona/ahYoutube/clipboardEDL/output.edl " + strings.ReplaceAll(lastKnownPath, "/Volumes/Drive/ahVids/", "/Volumes/Drive/ahVids/processed/") + " -t 10")
			}
		}

		// Wait for 500 milliseconds before checking the clipboard again
		time.Sleep(400 * time.Millisecond)
	}
}

func genEDLFromYoutubeMetaData(lines []string) string {
	var theLines []string
	for _, line := range lines {
		if strings.Contains(line, "Content found during:") {
			line := strings.ReplaceAll(line, "Content found during: ", "")
			startEnd := strings.Split(line, " - ")
			start := strings.Split(startEnd[0], ":")
			end := strings.Split(startEnd[1], ":")
			startString := ""
			endString := ""
			if len(start) == 3 {
				startHour, _ := strconv.Atoi(start[0])
				startMinute, _ := strconv.Atoi(start[1])
				startSecond, _ := strconv.Atoi(start[2])
				startTime := startHour*3600 + startMinute*60 + startSecond
				if startTime == 0 {
					startTime = 1
				}
				startString = strconv.Itoa(startTime)
			}
			if len(end) == 3 {
				endHour, _ := strconv.Atoi(end[0])
				endMinute, _ := strconv.Atoi(end[1])
				endSecond, _ := strconv.Atoi(end[2])
				endTime := endHour*3600 + endMinute*60 + endSecond
				endString = strconv.Itoa(endTime)
			}
			if len(start) == 2 {
				startMinute, _ := strconv.Atoi(start[0])
				startSecond, _ := strconv.Atoi(start[1])
				startTime := startMinute*60 + startSecond
				if startTime == 0 {
					startTime = 1
				}
				startString = strconv.Itoa(startTime)
			}
			if len(end) == 2 {
				endMinute, _ := strconv.Atoi(end[0])
				endSecond, _ := strconv.Atoi(end[1])
				endTime := endMinute*60 + endSecond
				endString = strconv.Itoa(endTime)
			}

			theLines = append(theLines, startString+" "+endString+" 0")
		}
	}
	//sort theLines startString by shortest time where startString is the first number in the line split by the first space

	sort.Slice(theLines, func(i, j int) bool {
		iStart, _ := strconv.Atoi(strings.Split(theLines[i], " ")[0])
		jStart, _ := strconv.Atoi(strings.Split(theLines[j], " ")[0])
		return iStart < jStart
	})

	// Iterate over the sorted lines to check for overlapping end and start times
	for i := 0; i < len(theLines)-1; i++ {
		currEndTime, _ := strconv.Atoi(strings.Split(theLines[i], " ")[1])
		nextStartTime, _ := strconv.Atoi(strings.Split(theLines[i+1], " ")[0])

		// If there's an overlap, adjust the end time of the current line
		if currEndTime > nextStartTime {
			// Adjust the end time of the current line
			parts := strings.Split(theLines[i], " ")
			parts[1] = strconv.Itoa(nextStartTime)
			theLines[i] = strings.Join(parts, " ")

			// Remove the next line
			theLines = append(theLines[:i+1], theLines[i+2:]...)
		}
	}

	out := ""
	for x, line := range theLines {
		if len(theLines) == x+1 {
			out += line
		} else if strings.Contains(line, " 0") {
			out += line + "\n"
		}
	}
	return out
}

```

**Pull request merged**
